
CREATE TABLE password_usage (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  password_type TEXT NOT NULL UNIQUE,
  used_by_matricula TEXT NOT NULL,
  used_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
